version: "3"

services:
  knowledge:
    build: "."
    image: "knowledge:v1.0.0"
    container_name: "knowledge"
    ports:
      - "8086:8086"
    volumes:
      - "${PWD}/chroma_db:/app/chroma_db"
      - "${PWD}/conf:/app/conf"
      - "/tmp:/tmp"
