name: "knowledge"
mode: "debug"
host: "127.0.0.1"
port: 8086

llm:
  # 可替换为 chat_gpt
  name: "wen_xin"

chat_glm:
  endpoint_url: "http://127.0.0.1:8000"
  max_token: 80000

chat_gpt:
  api_key: "aji***ill"
  max_token: 40000

wen_xin:
  api_key: "mUv***1Ll"
  secret_key: "0r3***UmY"

chroma:
  file_path: "./chroma_db"
  